= Concept for unified configuration format for Konnektor Clients

To establish a connection with a Konnektor each client requires a set of parameters which should be provided by the administrator. Such parameters include:

* Address of the Konnektor (url, port)
* Whether to use SSL or not
* Infomodell configuration (client, mandant, worklpace)
* Credentials (e.g. username, password, TLS certificate)

Typically each parameter is configured separately by client specific configuration means. This concept proposes a unified configuration format for all Konnektor clients. Such configurations can be provided by the administrators to all the clients in a standardized way.

*TODO: How to protect the credentials?*

[source,javascript]
----
{
  "url": "https://konnektor.example.com:8443",
  "mandantId": "M1",
  "workspaceId": "W1",
  "clientId": "C1",
  "credentials": {
    "type": "pkcs12",
    "pkcs12": "base64 encoded pkcs12",
    "password": "changeme",
  },
  "credentials": {
    "type": "der",
    "cert": "base64 encoded der",
    "key": "base64 encoded der",
  },
  "credentials": {
    "type": "pem",
    "cert": "pem as string",
    "key": "as pem string",
  },
  "credentials": {
    "type": "os",
    "id": "konnektor.example.com",
  },
  "credentials": {    
    "type": "basic",
    "username": "${KONNEKTOR_AUTH_BASIC_USERNAME}",
    "password": "${KONNEKTOR_AUTH_BASIC_PASSWORD}",
  }
}
----

Naming convention for the username which contains all required information to connect to the Konnektor. The username is used to identify the client and to determine the client specific configuration. The username is composed of the following parts:

* Mandant ID
* Workspace ID
* Client ID
* Authentication method
* Authentication parameters

[source,javascript]
----

openssl ecparam -name prime256v1 -genkey -noout -out client_prk.pem
openssl req -new -x509 -key client_prk.pem -out client_cert.pem -days 365 -subj "/C=DE/O=Organization/CN=C1"
openssl pkcs12 -export -out client_keypair.p12 -inkey client_prk.pem -in client_cert.pem -name "MyECCKey" -passout pass:changeme


.Sample configuration using client certificate authentication
[source,javascript]
----
{
  "url": "https://konnektor.example.com:8443",
  "mandantId": "M1",
  "clientId": "C1",
  "workspaceId": "W1",
  "credentials": {
    "type": "pkcs12",
    "pkcs12": "base64 encoded pkcs12",
    "password": "changeme",
  },
}

Security considerations: