= .kon: Einheitliches Konfigurationsformat für Konnektor-Clients

Um eine Verbindung mit einem Konnektor herzustellen, benötigt jeder Client eine Reihe von Parametern, die vom Administrator bereitgestellt werden sollten. Zu diesen Parametern gehören unter anderem:

* Adresse des Konnektors (URL, Port)
* Angabe, ob TLS verwendet werden soll oder nicht
* Infomodell-Konfiguration (Client, Mandant, Workspace)
* Credentials für den Zugang zur Konnektor-Schnittstellen (z. B. Benutzername/Passwort oder TLS-Zertifikat)

In der Regel wird jeder Parameter für jeden Client separat über clientspezifische Konfigurationsmechanismen eingestellt. Dieses Konzept schlägt ein einheitliches Konfigurationsformat für alle Konnektor-Clients vor. Durch ein solches Format können Administratoren standardisierte Konfigurationen an alle Clients übermitteln.

== Konfigurationsformat

Das Konfigurationsformat ist ein Objekt, das alle erforderlichen Parameter für die Konnektor-Konfiguration enthält. Unterschiedliche Kodierungen der Konfiguration sind möglich, z. B. JSON, YAML oder XML. Aufgrund der Einfachheit und der weiten Verbreitung wird in diesem Konzept JSON als Konfigurationsformat verwendet. 

* Alle Clients MÜSSEN JSON basierte Konfigurationen unterstützen.

[cols="m,a"]
|===
| Parameter | Beschreibung
| url 
| verpflichtend
| URL des Konnektors. URL muss das Protokoll (in der Regel `https://`), FQDN oder IP-Adresse und Port (falls abweichend vom standard Port) enthalten. URL darf nicht mit `/` enden. Durch einfügen von `/connector.sds` muss service directory service abfragbar sein. Beispiele:

  * `https://konnektor.example.com:8443`
  * `https://192.168.1.2`
  * `https://konnektor.example.com/kon1`

| mandantId
| Entspricht dem Mandanten-ID aus dem Infomodell. Wird als Aufrufkontext für die Konnektor-Schnittstellen verwendet.

| workspaceId
| Entspricht dem Workspace-ID aus dem Infomodell. Wird als Aufrufkontext für die Konnektor-Schnittstellen verwendet.

| clientSystemId
| Entspricht dem Client-ID aus dem Infomodell. Wird als Aufrufkontext für die Konnektor-Schnittstellen verwendet.


|===

[source,javascript]
----
{
  "url": "https://konnektor.example.com:8443",
  "mandantId": "M1",
  "workspaceId": "W1",
  "clientId": "C1",
  "credentials": {
    "type": "pkcs12",
    "pkcs12": "base64 encoded pkcs12",
    "password": "changeme",
  },
  "credentials": {
    "type": "der",
    "cert": "base64 encoded der",
    "key": "base64 encoded der",
  },
  "credentials": {
    "type": "pem",
    "cert": "pem as string",
    "key": "as pem string",
  },
  "credentials": {
    "type": "os",
    "id": "konnektor.example.com",
  },
  "credentials": {    
    "type": "basic",
    "username": "${KONNEKTOR_AUTH_BASIC_USERNAME}",
    "password": "${KONNEKTOR_AUTH_BASIC_PASSWORD}",
  }
}
----

Naming convention for the username which contains all required information to connect to the Konnektor. The username is used to identify the client and to determine the client specific configuration. The username is composed of the following parts:

* Mandant ID
* Workspace ID
* Client ID
* Authentication method
* Authentication parameters

[source,javascript]
----

openssl ecparam -name prime256v1 -genkey -noout -out client_prk.pem
openssl req -new -x509 -key client_prk.pem -out client_cert.pem -days 365 -subj "/C=DE/O=Organization/CN=C1"
openssl pkcs12 -export -out client_keypair.p12 -inkey client_prk.pem -in client_cert.pem -name "MyECCKey" -passout pass:changeme


.Sample configuration using client certificate authentication
[source,javascript]
----
{
  "url": "https://konnektor.example.com:8443",
  "mandantId": "M1",
  "clientId": "C1",
  "workspaceId": "W1",
  "credentials": {
    "type": "pkcs12",
    "pkcs12": "base64 encoded pkcs12",
    "password": "changeme",
  },
}

Security considerations: