#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from koap.gogenerator.generator import GoGenerator
import subprocess
import logging

logging.basicConfig(level=logging.INFO)


if __name__ == "__main__":
    gen = GoGenerator(
        "../koap-go",
        "github.com/spilikin/koap-go",
    )
    gen.scan_for_wsdl()
    gen.generate_all()

    # execute go fmt
    subprocess.run(["go", "fmt", "./..."], cwd="../koap-go/")
