#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from koap.gogenerator.generator import GoGenerator
import subprocess


if __name__ == "__main__":
    gen = GoGenerator(
        "../koap-go/pkg/koap/api_telematik/",
        "github.com/spilikin/koap-go/pkg/koap/api_telematik",
    )
    gen.scan_for_wsdl()
    gen.generate_all()

    # execute go fmt
    subprocess.run(["go", "fmt", "./..."], cwd="../koap-go/")
