#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from koap.gogenerator.generator import GoGenerator
import subprocess


if __name__ == "__main__":
    gen = GoGenerator(
        "../dsr/gemcard/pkg/koap/api_telematik/",
        "github.com/spilikin/healthcard/pkg/koap/api_telematik",
    )
    gen.add_service("EventService", "7.2.0")
    gen.add_service("CardService", "8.1.0")
    gen.add_service("CardService", "8.1.1")
    gen.add_service("CardService", "8.1.2")
    gen.generate_all()

    # execute go fmt
    subprocess.run(["go", "fmt", "./..."], cwd="../dsr/gemcard/pkg/koap/api_telematik")
